/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	volatile uint32_t *pClkctrlReg = (uint32_t*)0x40023830;
	volatile uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg = (uint32_t*)0x40020C14;

	//1.enable the clock for GPIOD peripheral in the AHB1ENR
	*pClkctrlReg |= 0x08;

	//2. Configure the mode of the IO pin as OUTPUT
	//a. clear 24th and 25th bit positionS
	*pPortDModeReg &= 0xFCFFFFFF;
	//b. make 24th bit position as 1(SET)
	*pPortDModeReg |= 0x01000000;

	while(1)
	{
	//3. SET 12th bit of the output data register to make I/O pin 12 HIGH
		*pPortDOutReg |= 0x1000;
		for(uint32_t i=0 ; i < 100000 ; i++ );

		*pPortDOutReg &= 0x0000;
		for(uint32_t i=0 ; i < 100000 ; i++ );
		}

}


